# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fada65321c6930ae9d56fd243d36ede85e9ce61979eb311436be4983bc40f4538fd33bdd0887a26a358921cab40e2eb7eec01b98c5148c8cc5800a4660e71e02

test:
  secret_key_base: e0df38e24331fbbe0980dadb68652b1d90c5389717a7fc6b45ce6802cd27572ce1aa12f0b0644d198b3de5007885040d27b28d1697ac35901966e19512e206e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
